# NumPy 


- Biblioteca de Algera Linear, a maioria das bibliotecas do Ecosistema PyData dependem de Numpy para rodarem.
- Construído em C, ou seja, roda mais rápido.

## Instalação

Anaconda:
conda install numpy

Pip:
pip install numpy

## Usando Numpy

In [1]:
import numpy as np

# Matrizes e arrays

## Numpy Arrays

Arrays são vetores 1D, e matrizes são vetores 2D

## Criando NumPy Arrays de uma lista

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Gera Arrays de 0s e 1s

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna elementos em um intervalo especificado

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Matriz identidade

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

### rand
Cria arrays gerados aleatoriamente no intervalo entre ``[0, 1)``.

In [16]:
np.random.rand(2)

array([ 0.22860932,  0.93831212])

In [17]:
np.random.rand(5,5)

array([[ 0.20532481,  0.49187054,  0.17630299,  0.94853524,  0.36973367],
       [ 0.35053609,  0.35697997,  0.94331018,  0.36422146,  0.86475308],
       [ 0.06106422,  0.89469126,  0.56113807,  0.34270127,  0.25606149],
       [ 0.44391918,  0.2502222 ,  0.91023075,  0.38375458,  0.85019014],
       [ 0.37926728,  0.01584115,  0.32953665,  0.79137366,  0.99141014]])

### randn

Retorna arrays distribuidos aleatoriamente por Standard Normalization

In [19]:
np.random.randn(2)

array([ 1.59575266, -1.39024326])

In [20]:
np.random.randn(5,5)

array([[-0.73939959, -0.10806385,  0.18701104,  1.95512409, -0.89427616],
       [-1.04845411, -0.4888431 , -0.15075231,  1.10231177, -0.38817802],
       [ 1.31744908, -0.56433485, -0.22955921,  0.35310861,  0.93036062],
       [-1.41675067,  0.01681007,  1.75729689, -0.52874756,  0.92631048],
       [-0.41007095,  1.2203684 ,  0.46478403,  0.45856551,  0.2356652 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).
Retorna inteiros aleatorios entre o intervalo especificado

In [21]:
np.random.randint(1,100)

11

In [22]:
np.random.randint(1,100,10)

array([ 6, 93, 75, 62, 67, 62, 84,  3, 14, 60])

## Atributos e Métodos de arrays

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([44, 44,  9, 20, 26,  1, 37,  2,  9, 37])

## Reshape
Retorna um array rearranjado

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin


In [27]:
ranarr

array([44, 44,  9, 20, 26,  1, 37,  2,  9, 37])

In [28]:
ranarr.max()

44

In [29]:
ranarr.argmax()

0

In [30]:
ranarr.min()

1

In [31]:
ranarr.argmin()

5

## Shape

Atributo para retornar a dimensão do array

In [ ]:
# Vector
arr.shape

In [ ]:
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

Checando o tipo do objeto

In [ ]:
arr.dtype

# Great Job!